# Generated by Django 5.2.1 on 2025-05-10 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog_app", "0002_alter_blogpost_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="blogpost",
            name="is_deleted",
            field=models.BooleanField(default=False),
        ),
    ]
